// digitekisi-mobile/src/app/auth/components/login/login.component.ts
import { NgIf } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { IonicModule } from '@ionic/angular';
import { FormsModule, ReactiveFormsModule, FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  standalone: true,
  imports: [IonicModule, RouterLink, NgIf, FormsModule, ReactiveFormsModule]
})
export class LoginComponent  implements OnInit {

  passwordIsVisible = signal(false)

  loginForm: FormGroup = new FormGroup({
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(7)]),
  })


  constructor() { }

  ngOnInit() {}

  onLogin(){
    
  }

  setPasswordVisibilityState(){
    this.passwordIsVisible.set(!this.passwordIsVisible())
  }

}

<div class="w-screen h-screen bg-gradient-primary relative">
  <img src="assets/icon/logo.svg" alt="" class="py-4 px-4">
  <form class="w-full py-2 px-2 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 flex flex-col items-center justify-center space-y-6" [formGroup]="loginForm">
    <ion-text class="font-bold text-darkOrange text-3xl w-[90%] mx-auto text-center">Welcome back to Digitekisi</ion-text>
    <div class="relative w-[95%] mx-auto">
      <img src="assets/icon/email_icon.svg" class="absolute top-3 right-3"/>
      <input type="email" class="w-full bg-transparent border-solid border-2 border-darkChocolate h-14 focus:border-darkOrange focus:outline-none placeholder:text-darkChocolate px-2 rounded-xl text-xl" placeholder="Email*" formControlName="email">
    </div>
    <div class="relative w-[95%] mx-auto">
      <img src="assets/icon/password_invisible.svg" class="absolute top-3 right-3" *ngIf="!passwordIsVisible()" (click)="setPasswordVisibilityState()"/>
      <img src="assets/icon/password_visible.svg" class="absolute top-3 right-3" *ngIf="passwordIsVisible()" (click)="setPasswordVisibilityState()"/>
      <input [type]="passwordIsVisible() ? 'text' : 'password'" class="w-full bg-transparent border-solid border-2 border-darkChocolate h-14 focus:border-darkOrange focus:outline-none placeholder:text-darkChocolate px-2 rounded-xl text-xl" placeholder="Password*" formControlName="password">
    </div>
    <button type="submit" class="capitalize text-2xl font-bold text-darkChocolate px-10 py-2 rounded-3xl bg-gradient-secondary flex items-center justify-center space-x-3" [disabled]="loginForm.invalid" (click)="onLogin()">
      <div class="hidden justify-center items-center">
        <div class="w-8 h-8 border-4 border-t-2 border-gray-200 rounded-full animate-spin" style="border-color: #00BFA5;"></div>
      </div>
      <div>Login</div>
      </button>
  </form>
  <ion-buttons class="absolute bottom-3 w-full flex items-center justify-between px-2">
    <ion-button class="capitalize" routerLink="/auth/password/forgot">Forgot password?</ion-button>
    <ion-button class="capitalize text-brightOrange" routerLink="/auth/signup/start">Create account</ion-button>
  </ion-buttons>
</div>

// digi_tekisi/src/pages/Login.jsx

import { useState } from "react";
import { useForm } from "react-hook-form";
import { FaEnvelope, FaLock, FaRegEye, FaRegEyeSlash } from "react-icons/fa";
import { Link } from "react-router-dom";
import Style from "./Welcome.module.css"

const Login = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
    watch,
  } = useForm();

  const [showPassword, setShowPassword] = useState(false);

  const toggleShowPassword = () => {
    setShowPassword(!showPassword);
  };

  const onSubmit = (data) => {
    console.log(data);
  };

  const password = watch("password");

  return (
    <div className={`${Style.back} flex flex-col items-center relative w-screen h-screen justify-center p-8`}>
    <div className="flex flex-col w-[100%] items-center relative bg-[#00BFA5] h-screen justify-center p-8">
      <div className="w-full max-w-md">
        <form
          onSubmit={handleSubmit(onSubmit)}
          className="bg-transparent flex flex-col justify-around px-8 pt-6 h-[20rem] pb-8 mb-4"
        >
          <h2 className="text-[28px] text-center font-normal capitalize text-[#ff9f00] mb-4">
            Welcome Back to DigiTekisi
          </h2>
          <div className="mb-4 relative p-2 border-2 border-gray-800 rounded-md">
            <input
            placeholder="Email*"
              type="email"
              className={` bg-transparent form-input w-[90%] ${
                errors.email ? "border-red-500" : ""
              }`}
              id="email"
              {...register("email", {
                required: "Email is required",
                pattern: {
                  value: /\S+@\S+\.\S+/,
                  message: "Invalid email address",
                },
              })}
            />
            <label
              htmlFor="email"
              className="absolute top-0 right-0 text-gray-700 font-medium mr-2 mt-2"
            >
              <FaEnvelope className="text-2xl" />
            </label>
            {errors.email && (
              <span className="text-red-500 text-sm">
                {errors.email.message}
              </span>
            )}
          </div>
          <div className="mb-4 relative p-2 border-2 border-gray-800 rounded-md">
            <input
            placeholder="Password*"
              type={showPassword ? "text" : "password"}
              className={`bg-transparent form-input w-[90%] ${
                errors.password ? "border-red-500" : ""
              }`}
              id="password"
              {...register("password", {
                required: "Password is required",
                minLength: {
                  value: 6,
                  message: "Password should be at least 6 characters",
                },
              })}
            />
            <label
              htmlFor="password"
              className="absolute top-0 right-0 text-gray-700 font-medium mr-2 mt-2 cursor-pointer"
              onClick={toggleShowPassword}
            >
              {showPassword ? (
                <FaRegEyeSlash className="text-2xl" />
              ) : (
                <FaRegEye className="text-2xl" />
              )}
            </label>
            {errors.password && (
              <span className="text-red-500 text-sm">
                {errors.password.message}
              </span>
            )}
          </div>
          <div className="flex items-center justify-center">
            <Link to="/">
              <button
                type="submit"
                className={`${Style.btn} bg-[#ff9f00] hover:bg-blue-700 text-gray-800 font-normal py-2 px-12 rounded-[20px] text-[24px]`}
              >
                Login
              </button>
            </Link>
          </div>
        </form>

        <div className="absolute flex items-center justify-between bottom-10 w-[20rem]">
          <Link to="/forgot">
            <p className="text-[16px] text-white font-normal">Forgot password?</p>
          </Link>

          <Link to="/signup">
            <p className="text-[16px] text-[#FF9F00] font-normal">
              Create account
            </p>
          </Link>
        </div>
      </div>
    </div>
    </div>
  // </div>
  );
            };

export default Login;
